# -*- coding: utf-8 -*-
"""pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""
from morphology_inference.roi_extractor import extract_roi_from_video
from morphology_inference.roi_loader import load_roi_images
from morphology_inference.morphology_ops import preprocess_binary, extract_target_sperm
from morphology_inference.predictor import extract_features, predict_morphology


def run_morphology_inference(
    video_path,
    tracking_csv,
    roi_dir
):
    # 1. extract ROI
    extract_roi_from_video(
        video_path=video_path,
        tracking_csv=tracking_csv,
        output_dir=roi_dir
    )

    # 2. load ROI
    rois = load_roi_images(roi_dir)

    results = []

    for item in rois:
        binary = preprocess_binary(item["image"])
        target = extract_target_sperm(binary)

        if target is None:
            continue

        features = extract_features(target)
        label = predict_morphology(features)

        results.append({
            "filename": item["filename"],
            "label": label,
            "features": features
        })

    return results
