# -*- coding: utf-8 -*-
"""casa_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

from motility.casa_features import compute_velocity, compute_linearity
from motility.labeling import label_motility
import pandas as pd

def run_casa_labeling(track_csv, output_csv):
    df = pd.read_csv(track_csv)

    v = compute_velocity(df)
    l = compute_linearity(df)

    feat = v.merge(l, on='particle')
    labeled = label_motility(feat)

    labeled.to_csv(output_csv, index=False)
    return labeled

