# -*- coding: utf-8 -*-
"""casa_features

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

import numpy as np
import pandas as pd

def compute_velocity(df, fps=30):
    df = df.sort_values(['particle', 'frame'])
    df['dx'] = df.groupby('particle')['x'].diff()
    df['dy'] = df.groupby('particle')['y'].diff()
    df['step_distance'] = np.sqrt(df['dx']**2 + df['dy']**2)
    df['velocity'] = df['step_distance'] * fps

    mean_velocity = (
        df.groupby('particle')['velocity']
        .mean()
        .reset_index(name='mean_velocity')
    )
    return mean_velocity


def compute_linearity(df):
    linearity = {}

    for p in df['particle'].unique():
        sub = df[df['particle'] == p].sort_values('frame')

        dx_steps = np.diff(sub['x'])
        dy_steps = np.diff(sub['y'])

        straight_distance = np.sqrt(
            (sub['x'].iloc[-1] - sub['x'].iloc[0])**2 +
            (sub['y'].iloc[-1] - sub['y'].iloc[0])**2
        )

        total_distance = np.sum(np.sqrt(dx_steps**2 + dy_steps**2))

        linearity[p] = straight_distance / total_distance if total_distance > 0 else 0

    return (
        pd.DataFrame.from_dict(linearity, orient='index', columns=['linearity'])
        .reset_index(names='particle')
    )

