# -*- coding: utf-8 -*-
"""labeling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbe-kvoKq-HK-VNpWuVLEhAczmHEF7jC
"""

import numpy as np

def label_motility(df):
    df['label'] = np.select(
        [
            df['mean_velocity'] < 5,
            (df['mean_velocity'] >= 25) & (df['linearity'] >= 0.4)
        ],
        [0, 2],     # 0=IM, 2=PR
        default=1  # 1=NP
    )
    return df

